name: cd

on:
  push:
    branches: ["release"]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: prod
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.18.2
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run ci:build
      - run: npm run ci:test
      - run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
